BoxLayout:
    orientation:'vertical'
    padding: 200
    spacing: '10dp'
    cols: 1
    Label: 
        text: "Digite seu peso e sua altura nessa ordem:"
        color: 0 , 1 , 1 , 1
        font_size: 25
    TextInput:
        id: peso
        text: ""
    TextInput:
        id: altura
        text: ""
    Button: 
        id: calcular
        text: "calcular"
        background_color: 0 , 1 , 1 , 1
    Label:
        id: mensagem
        text: ""